name: Node CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/node-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/node-ci.yml"

jobs:
  node:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: TypeCheck
        run: nr typecheck

      - name: Lint
        run: nr lint
